framework:
    rate_limiter:
        guest_analysis:
            policy: 'fixed_window'
            limit: 5
            interval: '1 day'

        user_analysis:
            policy: 'fixed_window'
            limit: 10
            interval: '1 day'