parameters:
    openrouter_api_key: '%env(OPENROUTER_API_KEY)%'
    serper_api_key: '%env(SERPER_API_KEY)%'
    apify_api_token: '%env(APIFY_API_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $openRouterApiKey: '%openrouter_api_key%'
            string $serperApiKey: '%serper_api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ApifyFacebookExtractorService:
        arguments:
            $apifyApiToken: '%apify_api_token%'

    App\Service\OfficialSourceDetectorService:
        arguments:
            $serperApiKey: '%serper_api_key%'

    App\Service\GroqAiService:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'
            $groqModel: '%env(GROQ_MODEL)%'